DROP TABLE IF EXISTS MOVIE_ACTORS;
DROP TABLE IF EXISTS MOVIE_GENRES;
DROP TABLE IF EXISTS ACTORS;
DROP TABLE IF EXISTS GENRE;
DROP TABLE IF EXISTS MOVIES;


CREATE TABLE ACTORS (
    Id BIGINT IDENTITY PRIMARY KEY,
    Name VARCHAR(120) NOT NULL,
    Surname VARCHAR(120) NOT NULL,
    Birthdate DATETIME2 NOT NULL,
    Deathdate DATETIME2,
    Gender VARCHAR(10) NOT NULL
);

CREATE TABLE GENRES (
    Id INTEGER IDENTITY PRIMARY KEY,
    Name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE MOVIES (
    Id BIGINT IDENTITY PRIMARY KEY,
    Title VARCHAR(120) NOT NULL,
    Duration BIGINT NOT NULL,
    ReleaseDate DATETIME2 NOT NULL
);

CREATE TABLE MOVIE_ACTORS (
    ActorId BIGINT NOT NULL REFERENCES ACTORS(Id),
    MovieId BIGINT NOT NULL REFERENCES MOVIES(Id),
    Role VARCHAR(240) NOT NULL
);

CREATE TABLE MOVIE_GENRES (
    GenreId INTEGER NOT NULL REFERENCES GENRES(Id),
    MovieId BIGINT NOT NULL REFERENCES MOVIES(Id),
    Significance INTEGER NOT NULL
);
