DROP TABLE IF EXISTS ACTORS;
DROP TABLE IF EXISTS GENRE;


CREATE TABLE ACTORS (
    Id BIGINT IDENTITY PRIMARY KEY,
    Name VARCHAR(120) NOT NULL,
    Surname VARCHAR(120) NOT NULL,
    Birthdate DATETIME2 NOT NULL,
    Deathdate DATETIME2,
    Gender VARCHAR(10) NOT NULL
);

CREATE TABLE GENRE (
    Id INTEGER IDENTITY  PRIMARY KEY,
    Name VARCHAR(30) NOT NULL UNIQUE
);
